// English (World English Bible) wording for beats that split a verse — keyed by scene id → beat index.
export const BEATS_EN = {
  'j18-kidron': {
    1: 'When Jesus had spoken these words, he went out with his disciples over the brook Kidron,',
    2: 'where there was a garden, into which he and his disciples entered.',
  },
  'j18-iam': {
    0: 'Judas then, having taken a detachment of soldiers and officers from the chief priests and the Pharisees,',
    1: 'came there with lanterns, torches, and weapons.',
    2: 'Jesus therefore, knowing all the things that were happening to him, went out,',
    3: 'and said to them, “Who are you looking for?”',
    4: 'They answered him, “Jesus of Nazareth.”',
    5: 'Jesus said to them, “I am he.”',
    6: 'Judas also, who betrayed him, was standing with them.',
  },
  'j18-letgo': {
    0: 'Again therefore he asked them, “Who are you looking for?”',
    1: 'They said, “Jesus of Nazareth.”',
    2: 'Jesus answered, “I told you that I am he.',
    3: 'If therefore you seek me, let these go their way,”',
    4: 'that the word might be fulfilled which he spoke,',
    5: '“Of those whom you have given me, I have lost none.”',
  },
  'j18-malchus': {
    0: 'Simon Peter therefore, having a sword, drew it,',
    1: 'and struck the high priest’s servant, and cut off his right ear.',
    2: 'The servant’s name was Malchus.',
    3: 'Jesus therefore said to Peter, “Put the sword into its sheath.',
    4: 'The cup which the Father has given me, shall I not surely drink it?”',
  },
  'j18-bound': {
    0: 'So the detachment, the commanding officer, and the officers of the Jews, seized Jesus',
    1: 'and bound him,',
    2: 'and led him to Annas first,',
    3: 'for he was father-in-law to Caiaphas, who was high priest that year.',
  },
  'j18-courtyard': {
    0: 'Simon Peter followed Jesus, as did another disciple.',
    1: 'Now that disciple was known to the high priest,',
    2: 'and entered in with Jesus into the court of the high priest;',
    3: 'but Peter was standing at the door outside.',
    4: 'So the other disciple, who was known to the high priest, went out and spoke to her who kept the door, and brought in Peter.',
    5: 'Then the maid who kept the door said to Peter, “Are you also one of this man’s disciples?”',
    6: 'He said, “I am not.”',
    7: 'Now the servants and the officers were standing there, having made a fire of coals, for it was cold. They were warming themselves.',
    8: 'Peter was with them, standing and warming himself.',
  },
  'j18-annas': {
    1: 'Jesus answered him, “I spoke openly to the world.',
    2: 'I always taught in synagogues, and in the temple, where the Jews always meet.',
    3: 'I said nothing in secret.',
    4: 'Why do you ask me?',
    5: 'Ask those who have heard me what I said to them.',
    6: 'Behold, these know the things which I said.”',
  },
  'j18-struck': {
    0: 'When he had said this, one of the officers standing by slapped Jesus with his hand,',
    1: 'saying, “Do you answer the high priest like that?”',
    2: 'Jesus answered him, “If I have spoken evil, testify of the evil;',
    3: 'but if well, why do you beat me?”',
  },
  'j18-rooster': {
    0: 'Now Simon Peter was standing and warming himself.',
    1: 'They said therefore to him, “You aren’t also one of his disciples, are you?”',
    2: 'He denied it, and said, “I am not.”',
    4: 'Peter therefore denied it again,',
    5: 'and immediately the rooster crowed.',
  },
  'j18-praetorium': {
    0: 'They led Jesus therefore from Caiaphas into the Praetorium.',
    1: 'It was early,',
    2: 'and they themselves didn’t enter into the Praetorium, that they might not be defiled, but might eat the Passover.',
    3: 'Pilate therefore went out to them,',
    4: 'and said, “What accusation do you bring against this man?”',
    6: 'Pilate therefore said to them, “Take him yourselves, and judge him according to your law.”',
    7: 'Therefore the Jews said to him, “It is not lawful for us to put anyone to death,”',
  },
  'j18-kingdom': {
    0: 'Pilate therefore entered again into the Praetorium,',
    1: 'called Jesus, and said to him, “Are you the King of the Jews?”',
    3: 'Pilate answered, “I’m not a Jew, am I?',
    4: 'Your own nation and the chief priests delivered you to me.',
    5: 'What have you done?”',
    6: 'Jesus answered, “My Kingdom is not of this world.',
    7: 'If my Kingdom were of this world, then my servants would fight, that I wouldn’t be delivered to the Jews.',
    8: 'But now my Kingdom is not from here.”',
  },
  'j18-truth': {
    0: 'Pilate therefore said to him, “Are you a king then?”',
    1: 'Jesus answered, “You say that I am a king.',
    2: 'For this reason I have been born, and for this reason I have come into the world, that I should testify to the truth.',
    3: 'Everyone who is of the truth listens to my voice.”',
    4: 'Pilate said to him, “What is truth?”',
  },
  'j18-barabbas': {
    0: 'When he had said this, he went out again to the Jews,',
    1: 'and said to them, “I find no basis for a charge against him.',
    2: 'But you have a custom, that I should release someone to you at the Passover.',
    3: 'Therefore do you want me to release to you the King of the Jews?”',
    4: 'Then they all shouted again, saying, “Not this man, but Barabbas!”',
    5: 'Now Barabbas was a robber.',
  },
};
