// English (World English Bible) wording for beats that split a verse — keyed by scene id → beat index.
export const BEATS_EN = {
  'j17-hour': {
    1: 'Jesus said these things, and lifting up his eyes to heaven, he said,',
    2: '“Father, the time has come.',
    3: 'Glorify your Son, that your Son may also glorify you;',
    4: 'even as you gave him authority over all flesh,',
    5: 'he will give eternal life to all whom you have given him.',
  },
  'j17-life': {
    0: 'This is eternal life,',
    1: 'that they should know you, the only true God,',
    2: 'and him whom you sent, Jesus Christ.',
  },
  'j17-work': {
    0: 'I glorified you on the earth.',
    1: 'I have accomplished the work which you have given me to do.',
    2: 'Now, Father, glorify me with your own self',
    3: 'with the glory which I had with you before the world existed.',
  },
  'j17-name': {
    0: 'I revealed your name to the people whom you have given me out of the world.',
    1: 'They were yours, and you have given them to me.',
    2: 'They have kept your word.',
    4: 'for the words which you have given me I have given to them,',
    5: 'and they received them,',
    6: 'and knew for sure that I came from you,',
    7: 'and they have believed that you sent me.',
  },
  'j17-pray': {
    0: 'I pray for them.',
    1: 'I don’t pray for the world, but for those whom you have given me, for they are yours.',
    2: 'All things that are mine are yours, and yours are mine,',
    3: 'and I am glorified in them.',
  },
  'j17-keep': {
    0: 'I am no more in the world, but these are in the world, and I am coming to you.',
    1: 'Holy Father, keep them through your name which you have given me,',
    2: 'that they may be one, even as we are.',
    3: 'While I was with them in the world, I kept them in your name. Those whom you have given me I have kept.',
    4: 'None of them is lost, except the son of destruction,',
    5: 'that the Scripture might be fulfilled.',
    6: 'But now I come to you,',
    7: 'and I say these things in the world, that they may have my joy made full in themselves.',
  },
  'j17-world': {
    0: 'I have given them your word.',
    1: 'The world hated them, because they are not of the world, even as I am not of the world.',
    2: 'I pray not that you would take them from the world,',
    3: 'but that you would keep them from the evil one.',
  },
  'j17-truth': {
    0: 'Sanctify them in your truth.',
    1: 'Your word is truth.',
    2: 'As you sent me into the world,',
    3: 'even so I have sent them into the world.',
    4: 'For their sakes I sanctify myself,',
    5: 'that they themselves also may be sanctified in truth.',
  },
  'j17-future': {
    0: 'Not for these only do I pray,',
    1: 'but for those also who believe in me through their word,',
    2: 'that they may all be one;',
    3: 'even as you, Father, are in me, and I in you,',
    4: 'that they also may be one in us;',
    5: 'that the world may believe that you sent me.',
  },
  'j17-glory': {
    0: 'The glory which you have given me, I have given to them;',
    1: 'that they may be one, even as we are one;',
    2: 'I in them, and you in me,',
    3: 'that they may be perfected into one;',
    4: 'that the world may know that you sent me,',
    5: 'and loved them, even as you loved me.',
  },
  'j17-love': {
    0: 'Father, I desire that they also whom you have given me be with me where I am,',
    1: 'that they may see my glory, which you have given me,',
    2: 'for you loved me before the foundation of the world.',
    3: 'Righteous Father, the world hasn’t known you,',
    4: 'but I knew you;',
    5: 'and these knew that you sent me.',
    6: 'I made known to them your name, and will make it known;',
    7: 'that the love with which you loved me may be in them, and I in them.”',
  },
};
