// English (World English Bible) wording for beats that split a verse — keyed by scene id → beat index.
export const BEATS_EN = {
  'j19-crown': {
    2: 'The soldiers twisted thorns into a crown, and put it on his head,',
    3: 'and dressed him in a purple garment.',
    4: 'They kept saying, “Hail, King of the Jews!”',
    5: 'and they kept slapping him.',
  },
  'j19-ecce': {
    0: 'Then Pilate went out again, and said to them,',
    1: '“Behold, I bring him out to you, that you may know that I find no basis for a charge against him.”',
    2: 'Jesus therefore came out, wearing the crown of thorns and the purple garment.',
    3: 'Pilate said to them, “Behold, the man!”',
    4: 'When therefore the chief priests and the officers saw him, they shouted, saying, “Crucify! Crucify!”',
    5: 'Pilate said to them, “Take him yourselves, and crucify him, for I find no basis for a charge against him.”',
    6: 'The Jews answered him, “We have a law, and by our law he ought to die,',
    7: 'because he made himself the Son of God.”',
  },
  'j19-power': {
    0: 'He entered into the Praetorium again, and said to Jesus, “Where are you from?”',
    1: 'But Jesus gave him no answer.',
    2: 'Pilate therefore said to him, “Aren’t you speaking to me?',
    3: 'Don’t you know that I have power to release you, and have power to crucify you?”',
    4: 'Jesus answered, “You would have no power at all against me, unless it were given to you from above.',
    5: 'Therefore he who delivered me to you has greater sin.”',
    6: 'At this, Pilate was seeking to release him,',
    7: 'but the Jews cried out, saying, “If you release this man, you aren’t Caesar’s friend!',
    8: 'Everyone who makes himself a king speaks against Caesar!”',
  },
  'j19-gabbatha': {
    0: 'When Pilate therefore heard these words, he brought Jesus out,',
    1: 'and sat down on the judgment seat at a place called “The Pavement”, but in Hebrew, “Gabbatha.”',
    2: 'Now it was the Preparation Day of the Passover, at about the sixth hour.',
    3: 'He said to the Jews, “Behold, your King!”',
    4: 'They cried out, “Away with him! Away with him! Crucify him!”',
    5: 'Pilate said to them, “Shall I crucify your King?”',
    6: 'The chief priests answered, “We have no king but Caesar!”',
    7: 'So then he delivered him to them to be crucified.',
    8: 'So they took Jesus and led him away.',
  },
  'j19-golgotha': {
    0: 'He went out, bearing his cross, to the place called “The Place of a Skull”,',
    1: 'which is called in Hebrew, “Golgotha”,',
    2: 'where they crucified him,',
    3: 'and with him two others, on either side one, and Jesus in the middle.',
  },
  'j19-title': {
    0: 'Pilate wrote a title also, and put it on the cross.',
    1: 'There was written, “JESUS OF NAZARETH, THE KING OF THE JEWS.”',
    2: 'Therefore many of the Jews read this title, for the place where Jesus was crucified was near the city;',
    3: 'and it was written in Hebrew, in Latin, and in Greek.',
    4: 'The chief priests of the Jews therefore said to Pilate,',
    5: '“Don’t write, ‘The King of the Jews,’ but, ‘he said, “I am King of the Jews.”’”',
  },
  'j19-tunic': {
    0: 'Then the soldiers, when they had crucified Jesus, took his garments and made four parts, to every soldier a part;',
    1: 'and also the coat.',
    2: 'Now the coat was without seam, woven from the top throughout.',
    3: 'Then they said to one another, “Let’s not tear it, but cast lots for it to decide whose it will be,”',
    4: 'that the Scripture might be fulfilled, which says, “They parted my garments among them. For my cloak they cast lots.”',
    5: 'Therefore the soldiers did these things.',
  },
  'j19-mother': {
    0: 'But there were standing by the cross of Jesus his mother,',
    1: 'and his mother’s sister, Mary the wife of Clopas, and Mary Magdalene.',
    2: 'Therefore when Jesus saw his mother, and the disciple whom he loved standing there,',
    3: 'he said to his mother, “Woman, behold, your son!”',
    4: 'Then he said to the disciple, “Behold, your mother!”',
    5: 'From that hour, the disciple took her to his own home.',
  },
  'j19-finished': {
    0: 'After this, Jesus, seeing that all things were now finished,',
    1: 'that the Scripture might be fulfilled, said, “I am thirsty.”',
    2: 'Now a vessel full of vinegar was set there;',
    3: 'so they put a sponge full of the vinegar on hyssop, and held it at his mouth.',
    4: 'When Jesus therefore had received the vinegar, he said, “It is finished.”',
    5: 'He bowed his head, and gave up his spirit.',
  },
  'j19-pierced': {
    0: 'Therefore the Jews, because it was the Preparation Day, so that the bodies wouldn’t remain on the cross on the Sabbath (for that Sabbath was a special one),',
    1: 'asked of Pilate that their legs might be broken, and that they might be taken away.',
    2: 'Therefore the soldiers came,',
    3: 'and broke the legs of the first, and of the other who was crucified with him;',
    4: 'but when they came to Jesus, and saw that he was already dead,',
    5: 'they didn’t break his legs.',
    6: 'However one of the soldiers pierced his side with a spear,',
    7: 'and immediately blood and water came out.',
  },
  'j19-witness': {
    0: 'He who has seen has testified, and his testimony is true.',
    1: 'He knows that he tells the truth, that you may believe.',
    2: 'For these things happened, that the Scripture might be fulfilled,',
    3: '“A bone of him will not be broken.”',
    4: 'Again another Scripture says,',
    5: '“They will look on him whom they pierced.”',
  },
  'j19-joseph': {
    0: 'After these things, Joseph of Arimathaea, being a disciple of Jesus, but secretly for fear of the Jews,',
    1: 'asked of Pilate that he might take away Jesus’ body.',
    2: 'Pilate gave him permission.',
  },
  'j19-spices': {
    0: 'He came therefore and took away his body.',
    1: 'Nicodemus, who at first came to Jesus by night, also came',
    2: 'bringing a mixture of myrrh and aloes, about a hundred Roman pounds.',
  },
  'j19-garden': {
    0: 'So they took Jesus’ body, and bound it in linen cloths with the spices,',
    1: 'as the custom of the Jews is to bury.',
    2: 'Now in the place where he was crucified there was a garden.',
    3: 'In the garden was a new tomb in which no man had ever yet been laid.',
  },
};
