#!/usr/bin/env python3
"""Downloads the Gospel of Mark, World English Bible (public domain), into data/mark-en.js."""
import html, json, pathlib, re, subprocess

OUT = pathlib.Path(__file__).resolve().parent.parent / 'data' / 'mark-en.js'

# Section headings, mirroring the Biblia Tysiąclecia structure so both languages share the same scenes.
HEADINGS = {
    1: [
        {'before': 1, 'kind': 'part', 'title': 'PREPARING FOR THE MINISTRY OF JESUS'},
        {'before': 1, 'kind': 'section', 'title': 'John the Baptist'},
        {'before': 9, 'kind': 'section', 'title': 'The Baptism of Jesus'},
        {'before': 12, 'kind': 'section', 'title': 'The Temptation of Jesus'},
        {'before': 14, 'kind': 'part', 'title': 'THE MINISTRY OF JESUS IN GALILEE'},
        {'before': 14, 'kind': 'part', 'title': 'THE BEGINNING OF THE MINISTRY'},
        {'before': 14, 'kind': 'section', 'title': 'The First Proclamation'},
        {'before': 16, 'kind': 'section', 'title': 'The Call of the First Disciples'},
        {'before': 21, 'kind': 'section', 'title': 'Teaching in Capernaum'},
        {'before': 23, 'kind': 'section', 'title': 'A Man Set Free'},
        {'before': 29, 'kind': 'section', 'title': 'In Peter’s House'},
        {'before': 32, 'kind': 'section', 'title': 'Many Healings'},
        {'before': 35, 'kind': 'section', 'title': 'Around Capernaum'},
        {'before': 40, 'kind': 'section', 'title': 'The Healing of a Leper'},
    ],
    2: [
        {'before': 1, 'kind': 'part', 'title': 'FIRST DISPUTES WITH THE LEADERS'},
        {'before': 1, 'kind': 'section', 'title': 'The Healing of a Paralytic'},
        {'before': 13, 'kind': 'section', 'title': 'The Call of Levi'},
        {'before': 18, 'kind': 'section', 'title': 'The Question of Fasting'},
        {'before': 23, 'kind': 'section', 'title': 'Grain Picked on the Sabbath'},
    ],
    3: [
        {'before': 1, 'kind': 'section', 'title': 'Healing on the Sabbath'},
        {'before': 7, 'kind': 'part', 'title': 'JESUS, WORKER OF WONDERS AND TEACHER'},
        {'before': 7, 'kind': 'section', 'title': 'The Crowds Flock to Him'},
        {'before': 13, 'kind': 'section', 'title': 'The Choosing of the Twelve'},
        {'before': 20, 'kind': 'section', 'title': 'The Crowd Presses In'},
        {'before': 22, 'kind': 'section', 'title': 'The Scribes’ Slander'},
        {'before': 31, 'kind': 'section', 'title': 'The True Family of Jesus'},
    ],
    4: [
        {'before': 1, 'kind': 'part', 'title': 'TEACHING IN PARABLES'},
        {'before': 1, 'kind': 'section', 'title': 'The Parable of the Sower'},
        {'before': 10, 'kind': 'section', 'title': 'The Purpose of the Parables'},
        {'before': 14, 'kind': 'section', 'title': 'The Sower Explained'},
        {'before': 21, 'kind': 'section', 'title': 'The Parable of the Lamp'},
        {'before': 24, 'kind': 'section', 'title': 'The Parable of the Measure'},
        {'before': 26, 'kind': 'section', 'title': 'The Growing Seed'},
        {'before': 30, 'kind': 'section', 'title': 'The Mustard Seed'},
        {'before': 33, 'kind': 'section', 'title': 'The End of the Parables'},
        {'before': 35, 'kind': 'part', 'title': 'PREPARING THE DISCIPLES'},
        {'before': 35, 'kind': 'section', 'title': 'The Storm on the Lake'},
    ],
}

def clean(s):
    s = re.sub(r'<[^>]+>', '', s)
    s = html.unescape(s).replace('\xa0', ' ')
    return re.sub(r'\s+', ' ', s).strip()

chapters = []
for ch in range(1, 17):
    raw = subprocess.run(['curl', '-sL', f'https://bolls.life/get-text/WEB/41/{ch}/'], capture_output=True, check=True).stdout
    verses = [clean(v['text']) for v in sorted(json.loads(raw), key=lambda v: v['verse'])]
    print(f'Mark {ch}: {len(verses)} verses')
    chapters.append({'verses': verses, 'headings': HEADINGS.get(ch, [])})

OUT.write_text(
    '// The Gospel according to Mark — World English Bible (public domain), via bolls.life\n'
    '// Generated by tools/fetch_mark_en.py — do not edit by hand.\n'
    'export const MARK_EN = ' + json.dumps({'book': 'The Gospel according to Mark', 'translation': 'World English Bible', 'chapters': chapters}, ensure_ascii=False, indent=1) + ';\n',
    encoding='utf-8')
print('wrote', OUT)
