#!/usr/bin/env python3
"""Downloads the Gospel of Mark, World English Bible (public domain), into data/mark-en.js."""
import html, json, pathlib, re, subprocess

OUT = pathlib.Path(__file__).resolve().parent.parent / 'data' / 'mark-en.js'

# Section headings, mirroring the Biblia Tysiąclecia structure so both languages share the same scenes.
HEADINGS = {
    4: [
        {'before': 1, 'kind': 'part', 'title': 'TEACHING IN PARABLES'},
        {'before': 1, 'kind': 'section', 'title': 'The Parable of the Sower'},
        {'before': 10, 'kind': 'section', 'title': 'The Purpose of the Parables'},
        {'before': 14, 'kind': 'section', 'title': 'The Sower Explained'},
        {'before': 21, 'kind': 'section', 'title': 'The Parable of the Lamp'},
        {'before': 24, 'kind': 'section', 'title': 'The Parable of the Measure'},
        {'before': 26, 'kind': 'section', 'title': 'The Growing Seed'},
        {'before': 30, 'kind': 'section', 'title': 'The Mustard Seed'},
        {'before': 33, 'kind': 'section', 'title': 'The End of the Parables'},
        {'before': 35, 'kind': 'part', 'title': 'PREPARING THE DISCIPLES'},
        {'before': 35, 'kind': 'section', 'title': 'The Storm on the Lake'},
    ],
}

def clean(s):
    s = re.sub(r'<[^>]+>', '', s)
    s = html.unescape(s).replace('\xa0', ' ')
    return re.sub(r'\s+', ' ', s).strip()

chapters = []
for ch in range(1, 17):
    raw = subprocess.run(['curl', '-sL', f'https://bolls.life/get-text/WEB/41/{ch}/'], capture_output=True, check=True).stdout
    verses = [clean(v['text']) for v in sorted(json.loads(raw), key=lambda v: v['verse'])]
    print(f'Mark {ch}: {len(verses)} verses')
    chapters.append({'verses': verses, 'headings': HEADINGS.get(ch, [])})

OUT.write_text(
    '// The Gospel according to Mark — World English Bible (public domain), via bolls.life\n'
    '// Generated by tools/fetch_mark_en.py — do not edit by hand.\n'
    'export const MARK_EN = ' + json.dumps({'book': 'The Gospel according to Mark', 'translation': 'World English Bible', 'chapters': chapters}, ensure_ascii=False, indent=1) + ';\n',
    encoding='utf-8')
print('wrote', OUT)
